#!/usr/bin/env python3
"""Ticket integrity gate (PreToolUse on Edit/Write/MultiEdit/NotebookEdit).

Direct edits to ticket files and the generated index are blocked for every
agent including the orchestrator — all mutations must go through
agenticflow/scripts/ticket.py, which enforces the state machine, role permissions, and
the audit trail. Archived tickets are immutable, period.
"""
import json
import os
import re
import sys

PROJECT = os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd())


def frozen_vision(rel):
    """True if `rel` names a VISION.md with its .frozen marker beside it —
    the stable link path and campaign storage paths alike (v0.3-E)."""
    return rel.endswith("VISION.md") and \
        os.path.exists(os.path.join(PROJECT, rel) + ".frozen")


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)
    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not path:
        sys.exit(0)
    rel = os.path.relpath(os.path.abspath(path), os.path.abspath(PROJECT))
    protected = (
        rel.startswith("agenticflow/tracker/tickets/"),
        rel.startswith("agenticflow/tracker/archive/"),
        rel == "agenticflow/tracker/INDEX.md",
        # campaign storage paths reach the same objects as the stable links —
        # both are gated, or the links are theater (v0.3-E)
        bool(re.match(r"agenticflow/visions/[^/]+/tracker/(tickets|archive)/", rel)),
        rel in ("agenticflow/docs/VISION.md", "agenticflow/docs/vision/VISION.md")
        and frozen_vision(rel),
        bool(re.match(r"agenticflow/visions/[^/]+/docs/VISION\.md$", rel))
        and frozen_vision(rel),
        # human-only blocklist tier: no agent (any session) may edit it — an
        # entry here must survive even a compromised vetting. The human edits
        # it in a plain editor, outside agent tooling.
        rel == "agenticflow/docs/BLOCKED_DEPS.md",
        # run.yaml is the human's control surface. While a run is live no
        # agent turns its own knobs (concurrency, gating, breakers — Ben's
        # 2026-07-29 ruling after a dispatcher raised builders 1->4 mid-run):
        # propose and continue, never self-serve. Outside a run (no RUNNING)
        # config edits stay legal — installs and upgrades need them.
        rel == "agenticflow/run.yaml"
        and os.path.exists(os.path.join(PROJECT, "agenticflow", "tracker",
                                        "RUNNING")),
    )
    # [near-ok] on an allowlist line clears the supply gate's typosquat check
    # for that name — so the marker itself must be human-only, or a fooled
    # toolsmith could wave its own squat through. The allowlist stays
    # toolsmith-editable; only edits INTRODUCING the marker are blocked.
    if rel == "agenticflow/docs/ALLOWED_DEPS.md":
        added = " ".join(str(tool_input.get(k, "")) for k in
                         ("new_string", "content", "new_source"))
        if "[near-ok" in added:
            try:
                from datetime import datetime, timezone
                ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
                with open(os.path.join(PROJECT, "agenticflow", "tracker", "gate_fires.tsv"),
                          "a", encoding="utf-8") as f:
                    f.write("%s\tticket_gate\tblocked agent [near-ok] marker\n" % ts)
            except Exception:
                pass
            sys.stderr.write(
                "TICKET GATE: [near-ok] markers in agenticflow/docs/ALLOWED_DEPS.md are "
                "human-only — the marker disarms the supply gate's typosquat "
                "check, so no agent may add one. Propose it in your ticket "
                "note or the digest; the human adds the marker in a plain "
                "editor.\n")
            sys.exit(2)

    if any(protected):
        try:  # fire-counter (curator trim-data); never fail the gate over logging
            from datetime import datetime, timezone
            ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            with open(os.path.join(PROJECT, "agenticflow", "tracker", "gate_fires.tsv"),
                      "a", encoding="utf-8") as f:
                f.write("%s\tticket_gate\tblocked direct edit of %s\n" % (ts, rel))
        except Exception:
            pass
        sys.stderr.write(
            "TICKET GATE: %s is not directly editable.\n"
            "- Tickets: use agenticflow/scripts/ticket.py (new/claim/transition/comment/compact) — "
            "it validates the state machine and keeps the audit trail.\n"
            "- INDEX.md is generated by agenticflow/scripts/dispatch.py.\n"
            "- Archived tickets and a frozen VISION.md are immutable.\n"
            "- agenticflow/docs/BLOCKED_DEPS.md is human-only; propose changes via the "
            "digest or agenticflow/tracker/proposals/.\n"
            "- agenticflow/run.yaml is the human's while a run is live: PROPOSE the "
            "change (notify.py attention event with the key, value, and why) "
            "and continue at current settings; the human edits the file.\n"
            % rel)
        sys.exit(2)
    sys.exit(0)


if __name__ == "__main__":
    main()
